# 请配置storage的类型，nfs或者glusterfs,默认为nfs.
storage: "nfs"

devMode: true

nfs:
  # 需要修改，请配置真实nfs服务ip
  server: "172.20.144.236"
  # 需要修改，请配置真实nfs服务目录
  path: "/opt/nfs"

# 请配置控制节点上部署的keepalived虚ip
ingressVip: 172.20.144.239
# 请配置控制节点同网段的未使用ip
externalIp: 172.20.144.235

# enable apisix
apisix:
  enabled: false
  baseUri: "kylincloud.org"

ntp:
  # 如果有上游地址请配置下列参数,否则不要修改
  upstreamServer: 127.127.1.1

mysql:
  # type: maxscale, dev, external
  # dev: 使用ha命名空间下的MySQL
  # maxscale: 使用maxscale中间件连接MySQL
  # external: 使用外部提供的MySQL，使用外部提供的MySQL时，需要填入URI, Port和有全部权限的用户名及密码
  type: "maxscale"
  devUri: "mysql.ha"
  maxscaleUri: "maxscale.module"
  externalUri: "172.0.0.1"
  externalPort: "3306"
  externalUser: "username"
  externalPwd: "password"

global:
  imagePullSecrets:
    - name: "regcred"
