#-------------------------------------------------------------------
# mongodb组件的配置
replicaCount: 3

image:
  agentImage: quay.io/mongodb/mongodb-agent:11.12.0.7388-1
  versionUpgradeHookImage: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
  readinessProbeImage: quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8
  mongoImage: mongo:4.2.6
  operatorImage: quay.io/mongodb/mongodb-kubernetes-operator:0.7.3
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

username: root
database: admin
password: Kcm.2021

# storageclass will use nfs-storage and nfs.enable should be true.
volumeType: "storageclass"
hostpathVolume:
  path: /opt/ssd/mongodb-datadir

persistence:
  mountPath: /bitnami/mongodb
  subPath: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  storageClassName: "nfs-storage"
