#-------------------------------------------------------------------
# mysql组件的配置

# 使用本地目录为hostpah，采用storageclass改为storageclass.
volumeType: "hostpath"
replicas: 1
persistentVolume:
  enabled: true
  size: 10Gi
  storageClass: nfs-storage
image:
  image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"
initImage:
  image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"
