#-------------------------------------------------------------------
# mysql组件的配置

# 使用本地目录为hostpah，采用storageclass改为storageclass.
volumeType: "hostpath"
replicas: 1
persistentVolume:
  enabled: true
  size: 10Gi
  storageClass: nfs-storage
image:
  image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"
initImage:
  image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"


# volumeType is storageclass or hostpath if set storageClassName
# it will use nfs-storage storageClassName.
volumeType: "storageclass"
hostpathVolume:
  enabled: false
  node: node1                   # 配置要调度到的节点的hostname
  path: /opt/ssd/mysql-datadir     # 配置要调度到的节点的目录
  type: DirectoryOrCreate

# 如需使用NFS，请修改hostpathVolume的enabled选项为false
# 将persistentVolume的enabled选项改为true,storageclass改为nfs-storage
persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: local-path
