stages:
  - build

.build: &build_ref
  stage: build
  script:
    - git show --stat $(git log | head -1 | awk '{print $2}') | grep image-list >/dev/null && bash mkiso.sh

build_amd64:
  <<: *build_ref
  variables:
    ARCH : 'amd64'
  image: registry.kylincloud.org/pub/dind/amd64:build-iso
  tags:
    - cached
    - amd64

build_arm64:
  <<: *build_ref
  variables:
    ARCH : 'arm64'
  image: registry.kylincloud.org/pub/dind/arm64:build-iso
  tags:
    - cached
    - arm64
