mysql:
  enabled: true
  replicas: 1
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: nfs-storage
  image:
    image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"
  initImage:
    image: "registry.kylincloud.org:4001/solution/ha/mysql/arm64/mysql:5.7"

#etcd:
#  enabled: false
#  replicaCount: 3
#  nodeAffinityPreset:
#    values: ["master1", "master2", "master3"]
#  persistence:
#    storageClassName: nfs-storage
#  image:
#    registry: "registry.kylincloud.org:4001"
#    repository: solution/ha/etcd/arm64/etcd
#    tag: v3.4.13

elasticsearch:
  enabled: true
  initContainer:
    image:
      image: "registry.kylincloud.org:4001/solution/deploy/arm64/busybox:1.28"
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: nfs-storage
  nfs:
    enable: false
  image:
    image: "registry.kylincloud.org:4001/solution/ha/elasticsearch/arm64/elasticsearch:7.9.1"

apisix:
  enabled: false
  replicaCount: 1
  apisix:
    image:
      image: "registry.kylincloud.org:4001/solution/ha/apisix/arm64/apisix:2.10.4-alpine"
    initImage:
      image: "registry.kylincloud.org:4001/solution/deploy/arm64/busybox:1.28"
  etcd:
    enabled: true
    host:
      - "http://apisix-etcd.apisix-system.svc.cluster.local:2379"  # host or ip e.g. http://172.20.128.89:2379
    prefix: "/apisix"
    timeout: 30
    replicaCount: 3
    nodeAffinityPreset:
      values: ["master1", "master2", "master3"]
    image:
      image: "registry.kylincloud.org:4001/solution/ha/etcd/arm64/etcd:v3.4.13"
  ingress-controller:
    enabled: true
    config:
      apisix:
      #【注意】一定要设置 gateway 所在的 namespace
        serviceNamespace: apisix-system
    serviceMonitor:
      enabled: true
      namespace: 'apisix-system'
      interval: 15s
    image:
      image: "registry.kylincloud.org:4001/solution/ha/apisix/arm64/apisix-ingress-controller:1.4.0"
    initContainer:
      image: "registry.kylincloud.org:4001/solution/deploy/arm64/busybox:1.28"
  dashboard:
    image:
      image: "registry.kylincloud.org:4001/solution/ha/apisix/arm64/apisix-dashboard:2.9.0"


mongodb:
  enabled: true
  image:
    image: "registry.kylincloud.org:4001/solution/ha/mongodb/arm64/mongo:4.4.2"
  sidecar:
    image:
      image: "registry.kylincloud.org:4001/solution/ha/mongodb/arm64/mongo-k8s-sidecar:20220217"
  job:
    image:
      image: "registry.kylincloud.org:4001/solution/ha/mongodb/arm64/mongo:4.4.2"
  replicaCount: 3
  persistence:
    enabled: true
    storageClassName: nfs-storage
  nfs:
    enable: false

redis-ha:
  enabled: true
  image:
    image: "registry.kylincloud.org:4001/solution/ha/redis/arm64/redis:5.0.12-alpine"
  replicas: 3
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: nfs-storage
  redis:
    customConfig: |
      dir "/data"
      port 6379
      maxmemory 0
      maxmemory-policy volatile-lru
      min-replicas-max-lag 5
      min-replicas-to-write 1
      rdbchecksum yes
      rdbcompression yes
      repl-diskless-sync yes
      save 900 1
      requirepass replace-default-auth
      masterauth replace-default-auth
  haproxy:
    enabled: true
    replicas: 3
    image:
      image: "registry.kylincloud.org:4001/solution/ha/redis/arm64/haproxy:2.0.4"
  auth: true
  # 不能使用特殊字符@#$等，最好使用字母+数字
  redisPassword: kylin123.

minio:
  enabled: true
  mode: distributed
  image:
    image: "registry.kylincloud.org:4001/solution/ha/minio/arm64/minio:RELEASE.2021-02-14T04-01-33Z"
  mcImage:
    image: "registry.kylincloud.org:4001/solution/ha/minio/arm64/mc:RELEASE.2021-02-14T04-28-06Z"
  accessKey: "admin"
  secretKey: "12341234"
  service:
    type: NodePort
    nodePort: 32000
  persistence:
    enabled: true
    storageClass: "nfs-storage"

#repo:
#  enabled: false
global:
  images:
    default: