apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5Lmt5bGluY2xvdWQub3JnOjQwMDEiOnsidXNlcm5hbWUiOiJjYW95dWFuemhpIiwicGFzc3dvcmQiOiI0OTA5MjQ1ODYiLCJlbWFpbCI6ImNhb3l1YW56aGlAa3lsaW5vcy5jbiIsImF1dGgiOiJZMkZ2ZVhWaGJucG9hVG8wT1RBNU1qUTFPRFk9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: apps
type: kubernetes.io/dockerconfigjson
